global using Microsoft.AspNetCore.Mvc;
global using DataAccessLayer.EntityFramework;
global using Microsoft.EntityFrameworkCore;
global using UI;
global using DataAccessLayer.Interfaces;
global using DataAccessLayer.Repositories;
global using Domain.Entities;
global using BusinessLogicLayer.Interfaces;
global using BusinessLogicLayer.Services;